"""Common database models used across services"""
from sqlalchemy import Column, Integer, String, JSON, DateTime, Boolean
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()


class Course(Base):
    """Course model"""
    __tablename__ = "courses"

    course_id = Column(Integer, primary_key=True, autoincrement=True)
    course_name = Column(String(200), nullable=False)
    course_credit = Column(Integer, nullable=False)
    course_type = Column(String(50), nullable=False)
    course_teacher_id = Column(Integer, nullable=False)
    course_time_begin = Column(Integer, nullable=False)
    course_time_end = Column(Integer, nullable=False)
    course_location = Column(String(100), nullable=False)
    course_capacity = Column(Integer, nullable=False)
    course_selected = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Student(Base):
    """Student model"""
    __tablename__ = "students"

    student_id = Column(Integer, primary_key=True, autoincrement=True)
    student_name = Column(String(100), nullable=False, unique=True)
    student_courses = Column(JSON, default=list)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Teacher(Base):
    """Teacher model"""
    __tablename__ = "teachers"

    teacher_id = Column(Integer, primary_key=True, autoincrement=True)
    teacher_name = Column(String(100), nullable=False, unique=True)
    teacher_courses = Column(JSON, default=list)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class User(Base):
    """User model for authentication"""
    __tablename__ = "users"

    user_id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(100), nullable=False, unique=True)
    password_hash = Column(String(255), nullable=False)
    user_type = Column(String(20), nullable=False)  # student, teacher, admin
    totp_secret = Column(String(32))  # For 2FA
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Admin(Base):
    """Admin model"""
    __tablename__ = "admins"

    admin_id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(100), nullable=False, unique=True)
    password_hash = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class RefreshToken(Base):
    """Refresh token storage"""
    __tablename__ = "refresh_tokens"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, nullable=False)
    token_hash = Column(String(255), nullable=False, unique=True)
    expires_at = Column(DateTime, nullable=False)
    is_revoked = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class RegistrationCode(Base):
    """Registration codes generated by admin"""
    __tablename__ = "registration_codes"

    id = Column(Integer, primary_key=True, autoincrement=True)
    code = Column(String(32), nullable=False, unique=True)
    user_type = Column(String(20), nullable=False)
    is_used = Column(Boolean, default=False)
    used_by = Column(Integer)
    created_by = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=False)


class ResetCode(Base):
    """2FA reset codes generated by admin"""
    __tablename__ = "reset_codes"

    id = Column(Integer, primary_key=True, autoincrement=True)
    code = Column(String(32), nullable=False, unique=True)
    user_id = Column(Integer, nullable=False)
    is_used = Column(Boolean, default=False)
    created_by = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=False)


class QueueTask(Base):
    """Queue task for course selection"""
    __tablename__ = "queue_tasks"

    task_id = Column(String(36), primary_key=True)
    student_id = Column(Integer, nullable=False)
    course_id = Column(Integer, nullable=False)
    task_type = Column(String(20), nullable=False)  # select, deselect
    status = Column(String(20), default="pending")  # pending, processing, completed, failed
    priority = Column(Integer, default=0)
    error_message = Column(String(500))
    retry_count = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    started_at = Column(DateTime)
    completed_at = Column(DateTime)
