"""Common database models used across services"""
from sqlalchemy import Column, Integer, String, JSON, DateTime, Boolean
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime, timezone

# Separate base classes for different service databases
DataBase = declarative_base()  # For data_node: courses, students, teachers
AuthBase = declarative_base()  # For auth_node: admins, tokens, codes
QueueBase = declarative_base()  # For queue_node: queue_tasks


class Course(DataBase):
    """Course model with enhanced scheduling and tagging system"""
    __tablename__ = "courses"

    course_id = Column(Integer, primary_key=True, autoincrement=True)
    course_name = Column(String(200), nullable=False)
    course_credit = Column(Integer, nullable=False)
    course_type = Column(String(50), nullable=False)
    course_teacher_id = Column(Integer, nullable=False)
    
    # Legacy time fields for backward compatibility
    course_time_begin = Column(Integer, nullable=True)
    course_time_end = Column(Integer, nullable=True)
    
    # New scheduling system: {"monday": [1,2,5], "wednesday": [3,4], ...}
    # Time slots: 1-4 (morning), 5-8 (afternoon), 9-11 (evening)
    course_schedule = Column(JSON, nullable=True)
    
    course_location = Column(String(100), nullable=False)
    course_capacity = Column(Integer, nullable=False)
    course_selected = Column(Integer, default=0)
    
    # New fields for enhanced course management
    course_tags = Column(JSON, default=list)  # Student must have matching tags
    course_notes = Column(String(500), default="")  # Additional information
    course_cost = Column(Integer, default=0)  # 0 for free courses
    is_active = Column(Boolean, default=True)
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))


class Student(DataBase):
    """Student model with authentication and 2FA"""
    __tablename__ = "students"

    student_id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(100), nullable=False, unique=True)
    password_hash = Column(String(255), nullable=False)
    student_name = Column(String(100), nullable=False)
    student_courses = Column(JSON, default=list)
    student_tags = Column(JSON, default=list)  # Tags for course enrollment eligibility
    totp_secret = Column(String(32))  # For 2FA (students only)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))


class Teacher(DataBase):
    """Teacher model with authentication (no 2FA)"""
    __tablename__ = "teachers"

    teacher_id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(100), nullable=False, unique=True)
    password_hash = Column(String(255), nullable=False)
    teacher_name = Column(String(100), nullable=False)
    teacher_courses = Column(JSON, default=list)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))


class Admin(AuthBase):
    """Admin model"""
    __tablename__ = "admins"

    admin_id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(100), nullable=False, unique=True)
    password_hash = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class RefreshToken(AuthBase):
    """Refresh token storage"""
    __tablename__ = "refresh_tokens"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, nullable=False)
    token_hash = Column(String(255), nullable=False, unique=True)
    expires_at = Column(DateTime, nullable=False)
    is_revoked = Column(Boolean, default=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class RegistrationCode(AuthBase):
    """Registration codes generated by admin"""
    __tablename__ = "registration_codes"

    id = Column(Integer, primary_key=True, autoincrement=True)
    code = Column(String(32), nullable=False, unique=True)
    user_type = Column(String(20), nullable=False)
    is_used = Column(Boolean, default=False)
    used_by = Column(Integer)
    created_by = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    expires_at = Column(DateTime, nullable=False)


class ResetCode(AuthBase):
    """2FA reset codes generated by admin"""
    __tablename__ = "reset_codes"

    id = Column(Integer, primary_key=True, autoincrement=True)
    code = Column(String(32), nullable=False, unique=True)
    user_id = Column(Integer, nullable=False)
    is_used = Column(Boolean, default=False)
    created_by = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    expires_at = Column(DateTime, nullable=False)





class QueueTask(QueueBase):
    """Queue task for course selection"""
    __tablename__ = "queue_tasks"

    task_id = Column(String(36), primary_key=True)
    student_id = Column(Integer, nullable=False)
    course_id = Column(Integer, nullable=False)
    task_type = Column(String(20), nullable=False)  # select, deselect
    status = Column(String(20), default="pending")  # pending, processing, completed, failed
    priority = Column(Integer, default=0)
    error_message = Column(String(500))
    retry_count = Column(Integer, default=0)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    started_at = Column(DateTime)
    completed_at = Column(DateTime)
